import{S as w,a as S,i as l}from"./assets/vendor-CsWjCmIl.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();const f=document.querySelector(".gallery"),m=document.querySelector(".loader");document.querySelector(".load-more");let q=new w(".gallery a");function y(e){const o=e.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <ul class="image-info">
        <li>👍 ${r.likes}</li>
        <li>👁️ ${r.views}</li>
        <li>💬 ${r.comments}</li>
        <li>⬇️ ${r.downloads}</li>
      </ul>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",o),q.refresh()}function P(){f.innerHTML=""}function g(){m.classList.add("visible")}function h(){m.classList.remove("visible")}function p(){const e=document.querySelector(".load-more");e&&(e.style.display="block")}function a(){const e=document.querySelector(".load-more");e&&(e.style.display="none")}function v(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}const B="https://pixabay.com/api/",E="51328495-a86ced526e026cbb82b9515b0",$=15;async function b(e,o=1){const r={key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:$};return(await S.get(B,{params:r})).data}let u="",i=1;const L=15;let d=0;const M=document.querySelector(".form"),O=document.querySelector('input[name="search-text"]'),x=document.querySelector(".load-more");a();M.addEventListener("submit",async e=>{e.preventDefault();const o=O.value.trim();if(!o){l.warning({message:"Please enter a search query."});return}u=o,i=1,P(),a(),g();try{const r=await b(u,i),{hits:s,totalHits:t}=r;if(d=t,s.length===0){l.info({message:"Sorry, there are no images matching your search query. Please try again!"}),a();return}y(s),d>i*L?p():a()}catch{l.error({message:"Something went wrong. Please try again later."}),a()}finally{h()}});x.addEventListener("click",async()=>{i+=1,g(),a();try{const e=await b(u,i),{hits:o}=e;if(o.length===0){a();return}y(o),v(),i*L>=d?(l.info({message:"We're sorry, but you've reached the end of search results."}),a()):p()}catch{l.error({message:"Failed to load more images."}),a()}finally{h()}});
//# sourceMappingURL=index.js.map
