import{S,a as q,i as l}from"./assets/vendor-CsWjCmIl.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=t(e);fetch(e.href,n)}})();const y=document.querySelector(".gallery"),m=document.querySelector(".loader"),g=document.querySelector(".load-more");let f=new S(".gallery a",{captionsData:"alt",captionDelay:250});function v(){f&&f.refresh()}function h(o){const r=o.map(t=>`
    <li class="gallery-item">
      <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" />
      </a>
      <ul class="image-info">
        <li>👍 ${t.likes}</li>
        <li>👁️ ${t.views}</li>
        <li>💬 ${t.comments}</li>
        <li>⬇️ ${t.downloads}</li>
      </ul>
    </li>
  `).join("");y.insertAdjacentHTML("beforeend",r),v()}function B(){y.innerHTML=""}function p(){m.classList.add("visible")}function L(){m.classList.remove("visible")}function b(){g.style.display="block"}function a(){g.style.display="none"}function $(){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}const E="https://pixabay.com/api/",M="51328495-a86ced526e026cbb82b9515b0",x=15;async function w(o,r=1){const t={key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:x};return(await q.get(E,{params:t})).data}let u="",i=1;const P=15;let d=0;const O=document.querySelector(".form"),A=document.querySelector('input[name="search-text"]'),H=document.querySelector(".load-more");a();O.addEventListener("submit",async o=>{o.preventDefault();const r=A.value.trim();if(!r){l.warning({message:"Please enter a search query."});return}u=r,i=1,B(),a(),p();try{const t=await w(u,i),{hits:s,totalHits:e}=t;if(d=e,s.length===0){l.info({message:"Sorry, there are no images matching your search query. Please try again!"}),a();return}h(s),d>i*P?b():a()}catch{l.error({message:"Something went wrong. Please try again later."}),a()}finally{L()}});H.addEventListener("click",async()=>{i+=1,p(),a();try{const o=await w(u,i),{hits:r}=o;if(r.length===0){a();return}h(r),$(),i*P>=d?(l.info({message:"We're sorry, but you've reached the end of search results."}),a()):b()}catch{l.error({message:"Failed to load more images."}),a()}finally{L()}});
//# sourceMappingURL=index.js.map
